app/plan/__init__.py
# coding:utf8

from flask import Blueprint

Plan = Blueprint('Plan',__name__)

from . import views

app/plan/views.py
# -*-coding:utf-8-*-
from . import Plan
from flask import render_template, Flask, request, jsonify
from app.Plan.SQLExec.plan import GetWorking, Data_Plan, SearchAllData, SearchEquipment, Data_DXNoPlan, Data_DXPlan, importData_PMC, Data_DXNoPlan_Type

from app.Plan.Models.plan import PMCPostData, GetEquipment, DXPostdata, DeleteDXPlan, DeletePMCData, ClearData
import time
import os


# --------------------- 生管
# 生管预排
@Plan.route('/PMC/<sWorkingProcedureName>')
def PMCIndex(sWorkingProcedureName):
    nCount = ''
    if sWorkingProcedureName in ('SXJ1', 'SXJ2', 'SE1', 'SE2'):
        nRow = sWorkingProcedureName.find('1')
        if nRow == -1:
            nRow = sWorkingProcedureName.find('2')
        nCount = sWorkingProcedureName[nRow:]
        sWorkingProcedureName = sWorkingProcedureName[:nRow]

    sWorkingName = GetWorking(sWorkingProcedureName)[0] + str(nCount)

    # NoPlanData = Data_NoPlan(sWorkingName)
    print('=======232======')
    PlanData = Data_Plan(sWorkingName)
    return render_template('Plan/PMC_DX.html', PlanData=PlanData)


# 生管预排搜索数据库中的数据
@Plan.route('/PMC/Search/<inputValue>')
def PMCSearch(inputValue):
    sValue = inputValue.split('_')[0]
    sWoring = inputValue.split('_')[1]
    nCount = ''
    if sWoring in ('SXJ1', 'SXJ2'):
        nRow = sWoring.find('1')
        if nRow == -1:
            nRow = sWoring.find('2')
        sWoring = sWoring[:nRow]
        nCount = sWoring[nRow:]
    sWoring = GetWorking(sWoring)[0]

    NoPlanData = Data_NoPlan(sWoring + str(nCount))
    returnData = SearchAllData(sValue, sWoring)

    returnHtml = '<ul id="bottom_ul" class="" style="margin: 0;padding: 0;">'
    for i in NoPlanData:
        returnHtml += ' \
                    <li class = "slot-item height40 marginLeft40" style = "padding: 0;" > \
                        <div class="clearfix height40"> \
                            <div class="hover_PMC" style="width:100%%;"> \
                                <table class="table"> \
                                    <tr style="text-align: center;"> \
                                        <td style="width: 4%%; line-height: 25px;" class="border-left">%s</td> <!-- 超时 --> \
                                        <td style="width: 10%%; line-height: 25px;" class="border-left">%s</td> <!-- 客户名称 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 布车号 --> \
                                        <td style="width: 8%%; line-height: 25px;" class="border-left">%s</td> <!-- 物料编号 --> \
                                        <td style="width: 3%%; line-height: 25px;" class="border-left">%s</td> <!-- LOT --> \
                                        <td style="width: 8%%; line-height: 25px;" class="border-left">%s</td> <!-- 卡号 --> \
                                        <td style="width: 9%%; line-height: 25px;" class="border-left">%s</td> <!-- 色号 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 投胚 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 上工段 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 现工段 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 下工段 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 生管交期 --> \
                                        <td style="width: 4%%; line-height: 25px;" class="border-left">%s</td> <!-- 业务交期 --> \
                                        <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 耗时 --> \
                                        <td style="width: 8%%; line-height: 25px;" class="border-left">%s</td> <!-- 营业课别 --> \
                                        <td style="width: 10%%; line-height: 25px;" class="border-left">%s</td> <!-- 工卡备注 --> \
                                        <td hidden>%s</td> \
                                    </tr> \
                                </table> \
                            </div> \
                        </div> \
                    </li> \
                ' % (i['nOverTime'], i['sCustomerName'], i['sLocation'], i['sMaterialNo'], i['sMaterialLot'], i['sCardNo'], i['sColorNo'], i['nFactInputQty'], i['sWorkingProcedureNameLast'], i['sWorkingProcedureNameCurrent'], i['sWorkingProcedureNameNext'], i['dReplyDate'], i['dDeliveryDate'], i['nPSTime'], i['sSalesGroupName'], i['sRemark'],  i['uppTrackJobGUID'])
    for i in returnData:
        # print()
        returnHtml += ' \
            <li class = "slot-item height40 marginLeft40 findOut" style = "padding: 0;" > \
                <div class="clearfix height40"> \
                    <div class="hover_PMC" style="width:100%%;"> \
                        <table class="table"> \
                            <tr style="text-align: center;"> \
                                <td style="width: 4%%; line-height: 25px;" class="border-left">%s</td> <!-- 超时 --> \
                                <td style="width: 10%%; line-height: 25px;" class="border-left">%s</td> <!-- 客户名称 --> \
                                <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 布车号 --> \
                                <td style="width: 8%%; line-height: 25px;" class="border-left">%s</td> <!-- 物料编号 --> \
                                <td style="width: 3%%; line-height: 25px;" class="border-left">%s</td> <!-- LOT --> \
                                <td style="width: 8%%; line-height: 25px;" class="border-left">%s</td> <!-- 卡号 --> \
                                <td style="width: 9%%; line-height: 25px;" class="border-left">%s</td> <!-- 色号 --> \
                                <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 投胚 --> \
                                <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 上工段 --> \
                                <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 现工段 --> \
                                <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 下工段 --> \
                                <td style="width: 4%%; line-height: 25px;" class="border-left">%s</td> <!-- 生管交期 --> \
                                <td style="width: 4%%; line-height: 25px;" class="border-left">%s</td> <!-- 业务交期 --> \
                                <td style="width: 5%%; line-height: 25px;" class="border-left">%s</td> <!-- 耗时 --> \
                                <td style="width: 8%%; line-height: 25px;" class="border-left">%s</td> <!-- 营业课别 --> \
                                <td style="width: 10%%; line-height: 25px;" class="border-left">%s</td> <!-- 工卡备注 --> \
                                <td hidden>%s</td> \
                            </tr> \
                        </table> \
                    </div> \
                </div> \
            </li> \
        ' % (i['nOverTime'], i['sCustomerName'], i['sLocation'], i['sMaterialNo'], i['sMaterialLot'], i['sCardNo'], i['sColorNo'], i['nFactInputQty'], i['sWorkingProcedureNameLast'], i['sWorkingProcedureNameCurrent'], i['sWorkingProcedureNameNext'], i['dReplyDate'], i['dDeliveryDate'], i['nPSTime'], i['sSalesGroupName'], i['sRemark'],  i['uppTrackJobGUID'])

    returnHtml += '</ul>'

    return returnHtml


# 生管预排 POST资料
@Plan.route('/PMC/PostData', methods=['GET', 'POST'])
def PMC_PostData():
    data = request.get_json()
    PMCPostData(data)
    return '生管数据更新'


# PMC操作说明
@Plan.route('/PMC/Operation')
def PMC_Operation():
    return render_template('plan/PMC_Operation.html')


# 导入数据
@Plan.route('/PMC/ImportData', methods=['GET', 'POST'])
def PMC_ImportData():
    data = request.get_json()
    print('================')
    print(data)
    importData_PMC(data)
    # print(data)
    return '导入成功'


# 删除数据
@Plan.route('/PMC/Delete', methods=['GET', 'POST'])
def PMC_Delete():
    data = request.get_json()
    for i in data:
        DeletePMCData(i)
    return '123'


# 定型
# 定型预排
@Plan.route('/DX/<sWorkingProcedureName>')
def DXIndex(sWorkingProcedureName):
    sEquipmentID = ''
    nCount = ''
    if sWorkingProcedureName in ('SXJ1', 'SXJ2', 'SE1', 'SE2'):
        nRow = sWorkingProcedureName.find('1')
        if nRow == -1:
            nRow = sWorkingProcedureName.find('2')
        nCount = sWorkingProcedureName[nRow:]
        sWorkingProcedureName = sWorkingProcedureName[:nRow]

    sWorkingName = GetWorking(sWorkingProcedureName)[0] + str(nCount)

    ReturnData = Data_DXNoPlan(sWorkingName)
    ReturnEquipment = GetEquipment('整理')
    ReturnDtlData = Data_DXPlan(sEquipmentID)
    return render_template('plan/DX.html', ReturnData=ReturnData, ReturnEquipment=ReturnEquipment, ReturnDtlData=ReturnDtlData)


# 定型AJAX
# 点击机台号进行数据的刷新
@Plan.route('/DX/AJAXDtl/<sEquipmentID>')
def checkEquipmentAJAX(sEquipmentID):
    data = Data_DXPlan(sEquipmentID)
    returnHTML = ''
    # print(data)
    for i in data:
        returnHTML += ' \
        <li class="slot-item" style="border: 0px;"> \
            <div class="clearfix"> \
                <div class="div-card float-left"> \
                    <div class="float-left" style="width: 120px; border-right: 1px solid #111; height: 100%%; text-align: center; line-height: 55px; text-align: center; line-height: 60px; background-color: %s"> \
                        <span>%s</span> \
                    </div> \
                    <div class="float-left" style="width: 96px; border-right: 1px solid #111;"> \
                        <div style="border-bottom: 1px solid #111; height: 30px; text-align: center; line-height: 30px;"> \
                            <span>%s</span> \
                        </div> \

app/templates/plan/DX.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>整理课排单</title>
    <link rel="stylesheet" href=" {{url_for('static',filename='bootstrap/css/bootstrap.css')}} ">
    <link rel="stylesheet" href=" {{url_for('static',filename='bootstrap/css/bootstrap-theme.css')}} ">
    <link rel="stylesheet" href=" {{url_for('static',filename='bootstrap/css/bootstrap-theme.min.css')}} ">
    <link rel="stylesheet" href=" {{url_for('static',filename='Plan/css/dragslot.css')}} ">
    <!-- <link rel="stylesheet" href=" {{url_for('static',filename='Scheduling/css/bootstrap_var.css')}} "> -->
    <link rel="stylesheet" href=" {{url_for('static',filename='Plan/css/plan_DX.css')}} ">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css"
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style type="text/css">
        .currentli {
            color: #186ecc;
            font-size: 15px;
            font-weight: 700;
        }

        .typeStyle {
            font-size: 17px;
            font-weight: 600;
        }
    </style>
</head>

<body id="body" class="">
    <div class="left-div float-left">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href=" {{ url_for('Plan.DXIndex', sWorkingProcedureName = 'PS' ) }} ">预定</a>
                    <a class="navbar-brand" href=" {{ url_for('Plan.DXIndex', sWorkingProcedureName = 'SXJ1' ) }} ">水洗1</a>
                    <a class="navbar-brand" href=" {{ url_for('Plan.DXIndex', sWorkingProcedureName = 'SXJ2' ) }} ">水洗2</a>
                    <a class="navbar-brand" href=" {{ url_for('Plan.DXIndex', sWorkingProcedureName = 'SE1' ) }} ">成定型1</a>
                    <a class="navbar-brand" href=" {{ url_for('Plan.DXIndex', sWorkingProcedureName = 'SE2' ) }} ">成定型2</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a onclick="refresh()">
                                <span>刷新</span>
                                <span class="sr-only"></span>
                            </a>
                        </li>
                        <li><a onclick="printPage()">打印<span class="sr-only"></span></a></li>
                        <li><a onclick="ClearData()" >清空预排<span class="sr-only"></span></a></li>
                        <li>
                            <a onclick="ExportExcel()">导出
                                <span class="sr-only"></span>
                            </a>
                        </li>
                        <li>
                            <a onclick="checkMasterialType('NET')" class="typeStyle">
                                <span>网布</span>
                                <span class="sr-only"></span>
                            </a>
                        </li>
                        <li>
                            <a onclick="checkMasterialType('BW')" class="typeStyle">
                                <span>平布黑白</span>
                                <span class="sr-only"></span>
                            </a>
                        </li>
                        <li>
                            <a onclick="checkMasterialType('Others')" class="typeStyle">
                                <span>平布其他</span>
                                <span class="sr-only"></span>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-form navbar-left">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="卡号/布种/工段/颜色" id="sInput">
                        </div>
                        <button class="btn btn-default" name="btnup" style="margin-top: 0px;" onclick="search()">
                            <span>搜索</span>
                        </button>
                    </div>
                </div>
            </div>
        </nav>
        <div style="overflow-y:scroll; ">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="width: 13%;">卡号</th>
                        <th style="width: 10%;">布种</th>
                        <th style="width: 10%;">颜色</th>
                        <th style="width: 6%;">幅宽</th>
                        <th style="width: 6%;">克重</th>
                        <th style="width: 6%;">投胚</th>
                        <th style="width: 6%;">耗时</th>
                        <th style="width: 6%;">温度</th>
                        <th style="width: 6%;">速度</th>
                        <th style="width: 7%;">上工段</th>
                        <th style="width: 7%;">当前工段</th>
                        <th style="width: 7%;">下工段</th>
                        <th style="width: 10%;">盒车</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="table-style" style="overflow-y:scroll; overflow-x:scroll; margin-top: -21px;">
            <table class="table table-bordered" id="dataTable">
                {% for i in ReturnData %}
                <tr onclick="onclicktr('{{i['uppTrackJobGUID']}}')" id="{{i['uppTrackJobGUID']}}"
                    style="background-color: {{i['sBorderColor']}}">
                    <td style="width: 13%;">{{i['sCardNo']}}</td>
                    <td style="width: 10%;">{{i['sMaterialNo']}}</td>
                    <td style="width: 10%;">{{i['sColorNo']}}</td>
                    <td style="width: 6%;">{{i['sProductWidth']}}</td>
                    <td style="width: 6%;">{{i['sProductGMWT']}}</td>
                    <td style="width: 6%;">{{i['nFactInPutQty']}}</td>
                    <td style="width: 6%;">{{i['nTime']}}</td>
                    <td style="width: 6%;">{{i['nTemp']}}</td>
                    <td style="width: 6%;">{{i['nSpeed']}}</td>
                    <td style="width: 7%;">{{i['sWorkingProcedureNameLast']}}</td>
                    <td hidden>{{i['uppTrackJobGUID']}}</td>
                    <td style="width: 7%;">{{i['sWorkingProcedureName']}}</td>
                    <td style="width: 7%;">{{i['sWorkingProcedureNameNext']}}</td>
                    <td style="width: 10%;">{{i['sLocation']}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="mid-div float-left" style="text-align: center; height:300px; margin-top: 60px;">
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXUp()" title="向上移动">
            <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXDown()" title="向下移动">
            <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXInsertData()" title="预排">
            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXDeleteData()" title="取消预排">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXTop()" title="置顶">
            <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXBottom()" title="置底">
            <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-lg" onclick="AJAXSave()" title="保存">
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        </button>
    </div>
    <div class="right-div float-left">
        <div style="height: 80px;">
            <ul class="nav nav-pills" id="eqLi">
                {% for i in ReturnEquipment %}
                <li role="presentation">
                    <a href="#" onclick="onclickCurrentli('{{i['ID']}}')" id="{{i['ID']}}">{{i['sEquipmentNo']}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div id="DataDiv">
            <div id="dragslot" class="">
                <div style="overflow-y:scroll;">
                    <ul id="SedData">
                        {% for i in ReturnDtlData %}
                        <li class="slot-item" style="border: 0px;">
                            <div class="clearfix">
                                <div class="div-card float-left">
                                    <div class="float-left"
                                        style="width: 120px; border-right: 1px solid #111; height: 100%; text-align: center; line-height: 55px; text-align: center; line-height: 60px; background-color: {{i['sBorderColor']}}">
                                        <span>{{i['sCardNo']}}</span>
                                    </div>
                                    <div class="float-left" style="width: 96px; border-right: 1px solid #111;">
                                        <div
                                            style="border-bottom: 1px solid #111; height: 30px; text-align: center; line-height: 30px;">
                                            <span>{{i['sMaterialNo']}}</span>
                                        </div>
                                        <div style="text-align: center; line-height: 30px;">
                                            <span>耗时:</span>
                                            <span>{{i['nTime']}}</span>
                                        </div>
                                    </div>
                                    <div hidden>{{i['uppTrackJobGUID']}}</div>
                                    <div class="float-left" style="width: 90px;">
                                        <div style="border-bottom: 1px solid #111; height: 30px; text-align: center; line-height: 30px;">
                                            <span>{{i['sWorkingProcedureNameCurrent']}}</span>
                                        </div>
                                        <div style="text-align: center; line-height: 30px;">
                                            <span>温度:</span>
                                            <span>{{i['nTemp']}}</span>
                                        </div>
                                    </div>
                                    <div hidden>{{i['sCardNo']}}</div>
                                    <div hidden>{{i['sMaterialNo']}}</div>
                                    <div hidden>{{i['sColorNo']}}</div>
                                    <div hidden>{{i['sProductWidth']}}</div>
                                    <div hidden>{{i['sProductGMWT']}}</div>
                                    <div hidden>{{i['nFactInPutQty']}}</div>
                                    <div hidden>{{i['nTime']}}</div>
                                    <div hidden>{{i['nTemp']}}</div>
                                    <div hidden>{{i['nSpeed']}}</div>
                                    <div hidden>{{i['sWorkingProcedureNameCurrent']}}</div>
                                </div>
                                <div class="float-left"
                                    style="width: 21px; height:60px; background-color:{{i['sColorBorder']}}; text-align: center;">
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="bottom-total">
                <ul class="nav nav-pills">
                    <li role="presentation" class="disabled" id="card-count">
                        <a href="#" style="color: crimson; font-weight: 700;">
                            <span>总卡数:</span>
                        </a>
                    </li>
                    <li role="presentation" class="disabled" id="card-time">
                        <a href="#" style="color:crimson; font-weight: 700;">
                            <span>总耗时:</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <script src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/bootstrap/js/jQuery-2.2.0.min.js"></script>
    <script type="text/javascript" src="/static/Plan/js/dragslot-ZL.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/xlsx.core.min.js"></script>
    <script type="text/javascript" src="/static/Plan/js/DX.js"></script>


</body> 

</html>

app/templates/plan/PMC_Operation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>生管预排说明</title>
</head>
<body>
    <ul>
        <li><span style="background-color:#FFFF00;">ERP系统急件</span></li>
        <li><span style="background-color:#FFA54F;">特急件</span></li>
        <li><span style="background-color:#186ecc;">选中效果</span></li>
        <li><span style="background-color:palevioletred;">搜索找到效果</span></li>
        <li><span style="background-color:palegreen;">当前预排效果</span></li>
        <li><span style="background-color:yellowgreen;">取消预排效果</span></li>
    </ul>
</body>
</html>